allowBuilds:
  '@google/genai': set this to true or false
  '@prisma/client': false
  '@prisma/engines': false
  prisma: false
  protobufjs: set this to true or false
  sharp: false
  unrs-resolver: false
