name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd Phone-marketplace
          npm install

      - name: Generate Prisma Client
        run: |
          cd Phone-marketplace
          npx prisma generate

      - name: Set environment variables
        run: |
          cd Phone-marketplace
          echo "DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy" >> $GITHUB_ENV

      - name: Run lint
        run: |
          cd Phone-marketplace
          npm run lint

      - name: Build project
        run: |
          cd Phone-marketplace
          npm run build
